import { Platform, Dimensions } from 'react-native';
import RF from "react-native-responsive-fontsize"
const win = Dimensions.get('window');
const logoImageMaxWidth = (win.width * 70) / 100;
const logoHeight = (logoImageMaxWidth * 150) / 503;
const logoContainerMainWidth = '70%';
const platform = Platform.OS;
// import Colors from '../../../native-base-theme/variables/material'
const { width, height } = Dimensions.get('window');

const styles = {
  bgImage: {
    alignItems: 'center',
    flex: 1,
    height: null,
    width: '100%',
  },
  loginScreenInnerScrollMainViewDesign: {
    width: logoContainerMainWidth,
    marginLeft: '15%',
    marginRight: '15%',
    height: '100%',
    flex: 1,
    // borderColor: 'black',
    // borderWidth: 1,
  },
  loginScreenChechBoxViewDesign: {
    height: RF(1.6),
    width: RF(1.6),
    /*height: 10,
    width: 10,*/
    marginRight: '10%',
    backgroundColor: 'white',
  },
  loginScreenErrorTwoDesign: {
    width: '95%',
    marginLeft: '2.5%',
    marginRight: '2.5%',
    //borderColor: 'black',
    //borderWidth: 1,
  },
  loginScreenScrollViewDesign: {
    //width: '100%',
    //flex: 1,
    height: '100%',
    // borderColor: 'green',
    // borderWidth: 2,
  },
  loginScreenMainViewDesign: {
    flex: 1,

    // top: 0,
    // bottom: 0,
    // left: 0,
    // right: 0,
    // borderColor: 'black',
    // borderWidth: 2,
  },
  loginScreenMainViewDesignOpacity: {
    flex: 1,
    // top: 0,
    // bottom: 0,
    // left: 0,
    // right: 0,
    // opacity: 1,
  },
  loginPageLoginError1TextDesign: {
    //fontSize: 12.5,
    fontSize: RF(2),
    marginTop: 5,
    width: '100%',
    color: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginPageLoginError2TextDesign: {
    fontSize: 13,
    marginTop: 5,
    width: '100%',
    color: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backgroundImage: {
    flex: 1,
    //resizeMode: 'cover',
    position: 'absolute',
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    backgroundColor: '#ffff00',
  },
  textParentView: {
    flex: 1,
    width: '90%',
    alignItems: 'center', justifyContent: 'center',
  },
  continuebutton: {
    flexDirection: 'row',
    height: RF(7),
    marginTop: RF(8),
    width: '90%',
    backgroundColor: 'white',
    borderRadius: RF(4),
    alignItems: 'center',
    justifyContent: 'center',
  },
  closebutton: {
    flexDirection: 'row',
    height: RF(7),
    marginTop: RF(2),
    width: '90%',
    backgroundColor: 'white',
    borderRadius: RF(4),
  },
  sendEmailButton: {
    flexDirection: 'row',
    height: RF(7),
    marginTop: RF(8),
    width: '100%',
    backgroundColor: 'white',
    borderRadius: RF(4),
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeModalbutton: {
    flexDirection: 'row',
    height: RF(7),
    marginTop: RF(2),
    width: '100%',
    backgroundColor: 'white',
    borderRadius: RF(4),
  },
  continuebuttonTouchable: {
    // marginTop: RF(1.2),
    // marginBottom: RF(1.2),
    // width: '90%',
    // height: RF(5.2),
    // backgroundColor: '#FFFFFF',
    // borderRadius: RF(2.9),
    // flex: 1,
    // flexDirection: 'row',

    //flexDirection: 'row',
    height: RF(7),
    width: '100%',
    //marginTop: RF(8),
    width: '100%',
    //backgroundColor: 'white',
    borderRadius: RF(4),
    alignItems: 'center',
    justifyContent: 'center',
    //borderColor: 'black',
    //borderWidth: 1,
  },
  continuebuttonImage: {
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: 'center',
    // borderColor: 'green',
    // borderWidth: 1,
    //flex: 1,
    //marginTop: RF(1), 
    //marginBottom: RF(1.6), 
    //marginRight: RF(2), 
    //marginLeft: RF(2),
    //borderColor: 'blue',
    //borderWidth: 1,
  },
  continuebuttonView: {
    paddingRight: 5, height: '100%', width: '50%', justifyContent: 'center'
  },
  continuebutton1: {
    //flexDirection: 'row', height: RF(7), marginTop: RF(2), width: '90%', backgroundColor: 'white', borderRadius: RF(4),
    flexDirection: 'row',
    height: RF(7),
    marginTop: RF(2),
    width: '90%',
    backgroundColor: 'white',
    borderRadius: RF(4),
    alignItems: 'center',
    justifyContent: 'center',
  },
  link: {
    flexDirection: 'row', height: RF(7), marginTop: RF(2), width: '90%'
  },
  rounduttonStylesignIn: {
    borderWidth: 1,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    width: RF(24),
    height: RF(6),
    backgroundColor: '#fff',
    borderRadius: RF(50),
  },
  rounduttonStylesignup: {
    borderWidth: 1,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    width: RF(24),
    height: RF(6),
    backgroundColor: '#FFB600',
    borderRadius: RF(50),
    marginLeft: 10
  },
  rounduttonStylesignInS: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    width: RF(22),
    height: RF(6),
    backgroundColor: '#fff',
    borderRadius: RF(22),
  },
  rounduttonStylesignupS: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    width: RF(22),
    height: RF(6),
    backgroundColor: '#FFB600',
    borderRadius: RF(22),
    marginLeft: 10
  },
  ImageStyle: {
    // marginTop: 5,
    // padding: 5,
    height: 20,
    width: 20,
    resizeMode: 'stretch',
    alignItems: 'center',
    borderColor: 'white',
  },
  ImageStyleEmailIcon: {
    // marginTop: 5,
    // padding: 5,

    // height: RF(2.5),
    // width: RF(2.5),
    // resizeMode: 'stretch',
    // alignItems: 'flex-start',
    // justifyContent: 'space-between',

    height: 20,
    width: 20,
    //resizeMode: 'stretch',
    marginLeft: 'auto',
    marginRight: 'auto',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    borderColor: 'white',
    //borderColor: 'blue',
    //borderWidth: 1,
  },
  textView: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#FFFF',
    //borderColor:'red',
    //borderWidth:1,
  },
  confirmMessage: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    color: 'white',
    fontFamily: 'Quicksand-Regular',
    fontSize: RF(2.5)
  },
  textBoxView: {
    flex: 1,
    // marginTop: RF(2),
    paddingLeft: 5,
    height: RF(6),
    width: '90%',
    fontSize: RF(2.5),
    color: '#FFFFFF',
    fontFamily: 'Quicksand-Regular',
    marginLeft: RF(2)
  },
  forgetTextBoxView: {
    flexDirection: 'row',
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
    height: RF(7),
    marginTop: RF(5),
    //borderColor:'red',
    //borderWidth:1,
  },
  logoImageView: {
    height: 150, width: 300
  },
  logoImageParentView: {
    alignItems: 'center', justifyContent: 'center'
  },
  mainView: {
    flex: 1, backgroundColor: '#FFBB00', borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center'
  },
  logoImage: {
    //position: 'absolute',
    //height: 'auto',
    //width: 'auto',
    //backgroundColor: '#2f2fe7',
    //backgroundColor: 'rgba(52, 52, 52, 0.8)',
    marginTop: 100,
    height: logoHeight,
    width: logoImageMaxWidth,
  },
  loginPageUpperTextDesign: {
    //fontSize: 12,
    fontSize: RF(1.7),
    marginTop: 15,
    width: '100%',
    color: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    fontFamily: 'Lato',
  },
  loginPageUpperTextDesignSecond: {
    //fontSize: 12,
    fontSize: RF(1.7),
    width: '100%',
    color: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    fontFamily: 'Lato',
    marginBottom: 20,
  },
  loginPageTextDesign: {
    fontSize: 18,
    marginTop: 5,
    width: '100%',
    color: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: 'Lato',
    paddingBottom: 5,
  },
  TextInputLoginEmailDesign: {
    //marginBottom: RF(1),
    //fontsize: RF(3),
    //borderRadius: RF(3.5),
    height: RF(10),
    //backgroundColor: 'rgba(255,255,255,0.2)',
    //backgroundColor: '#c9c9c9',
    //backgroundColor: "rgba(201, 201, 201,0.5)",
    width: '100%',
    // color: '#ffffff',
    // paddingLeft: 7,
    // opacity: 2,
    // zIndex: 2,
    // borderColor: 'black',
    // borderWidth: 1,
  },
  TextInputLoginPasswordDesign: {
    //fontsize: RF(3),
    //borderRadius: RF(3.5),
    height: RF(10),
    //backgroundColor: 'rgba(255,255,255,0.2)',
    //backgroundColor: '#c9c9c9',
    //backgroundColor: "rgba(201, 201, 201,0.5)",
    width: '100%',
    // color: '#ffffff',
    // paddingLeft: 7,
    // opacity: 2,
    // zIndex: 2,
    //borderColor: 'black',
    //borderWidth: 1,
  },
  loginTermsView: {
    //flex: 1,
    paddingTop: 0,
    //marginTop: 12,
    flexDirection: "row",
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 30,
    //borderColor: 'black',
    //borderWidth: 1,
  },
  loginAppButtonViewDesign: {
    marginTop: 20,
    width: '50%',
    marginLeft: '25%',
    marginRight: '25%',
    alignItems: 'center',
    justifyContent: 'center',
    height: 10,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    // borderColor: 'black',
    // borderWidth: 1,
  },
  loginAppButtonDesign: {
    borderRadius: 18,
    backgroundColor: '#fddf41',
    width: 120,
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
  },
  leaderboardTabViewInnerBoxRidesDesignHovered: {
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 18,
    zIndex: 0,
    flex: 1,
    width: 120,
    height: 35,
    backgroundColor: '#920C00',
    // borderColor: 'black',
    // borderWidth: 1,
  },
  leaderboardTabViewInnerBoxTextDesignSelected: {
    alignSelf: 'center',
    justifyContent: 'space-between',
    alignItems: 'center',
    color: '#FFFFFF',
    fontWeight: 'bold',
    //flex: 1,
    fontFamily: 'Lato',
    fontSize: RF(1.7),
    //marginTop: 10,
  },
  leaderboardTabViewInnerBoxTextDesignSelectedSignUp: {
    alignSelf: 'center',
    justifyContent: 'space-between',
    alignItems: 'center',
    color: '#FFFFFF',
    fontWeight: 'bold',
    //flex: 1,
    fontFamily: 'Lato',
    fontSize: RF(1.7),
    //marginTop: 10,
  },
  linearGradiantRidesStyles: {
    justifyContent: 'space-between',
    width: 120,
    zIndex: 0,
    alignItems: 'center',
    flex: 1,
    borderRadius: 18,
    height: 35,
    marginBottom: 25,
  },
  linearGradiantLoginAppButtonDesign: {
    borderRadius: 18,
    width: 120,
    height: 35,
    marginLeft: '10%',
    marginRight: '10%',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 25,
  },
  signInTextStyle: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 9,
    color: '#37354C',
    fontSize: 13,
  },
  termsOfService: {
    //fontSize: 10,
    fontSize: RF(1.8),
    color: '#ffffff',
    //fontFamily: 'Lato',
    //textDecorationLine: 'underline',
  },
  forgotPassword: {
    fontSize: RF(2.5),
    color: 'white',
    fontFamily: 'Lato',
  },
  forgotPasswordParentView: {
    fontSize: 15,
    fontWeight: 'bold',
    fontFamily: 'Lato',
    color: '#ffffff',
    width: '100%'
  },
  rowStyle: {
    //width:'90%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: RF(2.5)
  },
  rowStyleSignup: {
    width: '90%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: RF(2.5)
  },
  termsOfServiceUndelineText: {
    fontSize: 16,
    color: '#ffffff',
    textDecorationLine: 'underline',
    marginLeft: 5,
    fontFamily: 'Lato',
  },
  checkBoxAgreeTermsAndCondition: {
    marginRight: '10%',
    color: "white",
    backgroundColor: '#808080',
  },
  emailInputMainViewDesign: {
    marginTop: RF(0.8),
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginTermsViewText: {
    //width: '90%',
    flex: 1,
    flexDirection: "row",
    alignItems: 'center',
    justifyContent: "flex-start",
  },
  checkBoxAgreeTermsAndConditionOuterDesign: {
    width: 27,
    alignItems: 'center',
    justifyContent: "center",
    alignSelf: 'stretch',
    marginRight: 0,
    right: 0,
  },
  forgotPasswordDesign: {
    justifyContent: "center",
    alignSelf: 'stretch',
    marginRight: 0,
    right: 0,
    alignItems: 'flex-end',
    alignContent: 'flex-end',
    alignSelf: 'flex-end',
    marginRight: 5,
  },
  loginPageSignInButtonViewDesign: {
    height: '100%',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loginPageSignUpButtonViewDesign: {
    height: '100%',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loginPageSignInButtonTextDesign: {
    alignSelf: 'center',
    justifyContent: 'space-between',
    alignItems: 'center',
    color: '#FFFFFF',
    fontWeight: 'bold',
    flex: 1,
    fontFamily: 'Lato',
    marginTop: 10,
  },
  loginPageFBLoginButtonViewDesign: {
    height: '100%',
    width: '100%',
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonContainer: {
    flex: 1,
  },
  leaderboardTabViewInnerBoxTextDesignSelectedFBLogin: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontFamily: 'Lato',
    alignItems: 'center', justifyContent: 'center',
  },
  loginWithFBTouchableOpacityDesign: {
  },
  largeButton: {
    color: '#ffa500',
    //height: '100%',
    //width: '100%',
    alignItems: "center",
    //justifyContent: "center",
    justifyContent: 'center',
    // marginTop: 'auto',
    // marginBottom: 'auto',
    //marginLeft: 'auto',
    //marginRight: 'auto',
    //justifyContent: 'space-between',
    //fontSize: RF(2.7),
    //borderColor: 'blue', borderWidth: 1,
  },
  largeButtonGuestUser: {
    color: '#ffa500',
    //height: '100%',
    //width: '100%',
    alignItems: "center",
    //justifyContent: "center",
    justifyContent: 'center',
    // marginTop: 'auto',
    // marginBottom: 'auto',
    //marginLeft: '11%',
    //marginRight: '11%',
    // marginTop: 'auto',
    // marginBottom: 'auto',
    //marginLeft: 'auto',
    //marginRight: 'auto',
    //justifyContent: 'space-between',
    //fontSize: RF(2.7),
    //borderColor: 'blue', borderWidth: 1,
  },
  forgetButton: {
    color: '#ffa500',
    // marginTop: 7,
    alignItems: "center",
    justifyContent: "center",
    fontSize: RF(3),
  },
  logoContainerWidth: '70%',
  platform: platform,
  text: {
    color: '#fff',
    marginTop: 10,
    fontFamily: 'Lato'
  },
  modal: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: RF(20),
    backgroundColor: '#FFA400'
  },
  modal2: {
    height: 230,
    backgroundColor: '#3B5998'
  },
  // modal3: {
  //   height: 300,
  //   width: 300
  // },
  modal4: {
    height: 400,
    width: 300
  },
  modal: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: RF(20),
    backgroundColor: '#FFA400',
    borderRadius: RF(4)
  },
  modal3: {
    height: RF(40),
    width: 300
  },
  modal5: {
    height: RF(37),
    width: 300
  },
  forgotPasswordModal: {
    flex: 1,
    width: '100%'
  },
  forgotPasswordModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#CCCCCC',
    width: '100%',
    height: RF(10),
  },
  forgotPasswordModalTitle: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    marginLeft: '5%'
  },
  forgotPasswordModalTitleText: {
    color: '#fff',
    fontFamily: 'Quicksand-Bold',
    fontSize: RF(3),
  },
  // forgotPasswordModalCloseButton: {
  //   alignItems: 'flex-end',
  //   justifyContent: 'flex-end',
  //   marginRight: '5%'
  // },
  forgotPasswordModalContent: {
    flexDirection: 'column',
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
    height: RF(5),
    marginTop: RF(1),
    marginLeft: '5%',
    marginRight: '5%'
  },
  confirmEmailModalContent: {
    flexDirection: 'column',
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
    height: RF(10),
    marginTop: RF(1),
    marginLeft: '5%',
    marginRight: '5%'
  },
  forgotPasswordModalButtonView: {
    flexDirection: 'column',
    width: '90%',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: RF(6)
  },
  confirmEmailModalButtonView: {
    flexDirection: 'column',
    width: '90%',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: RF(8)
  },
  camOpenCamera: {
    backgroundColor: '#fff',
    width: '80%',
    borderRadius: RF(5),
    height: RF(7)
  },
  forgotPasswordModalButtonText: {
    color: '#ffaa1a',
    fontFamily: 'Quicksand-Regular',
    textAlign: 'center',
    padding: RF(2)
  },
  forgotPasswordModalCloseButton: {
    backgroundColor: '#fff',
    width: '80%',
    borderRadius: RF(5),
    height: RF(7),
    marginTop: RF(1.5)
  },
  forgotPasswordModalHeaderCloseButton: {
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    marginRight: '5%'
  },
  forgotPasswordModalCloseButtonText: {
    color: '#ffaa1a',
    fontFamily: 'Quicksand-Regular',
    textAlign: 'center',
    padding: RF(2)
  },
  camOpenImage: {
    backgroundColor: '#ffaa1a',
    width: '80%',
    borderRadius: RF(5),
    height: RF(7),
    marginTop: RF(1.5)
  },
  camOpenCameraText: {
    color: '#fff',
    fontFamily: 'Quicksand-Regular',
    textAlign: 'center',
    padding: RF(2)
  },
  validationModal: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: RF(20),
    backgroundColor: '#FFA400'
  },
  btn: {
    margin: 10,
    backgroundColor: '#3B5998',
    color: 'white',
    padding: 10
  },
  loading: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    width: '100%',
    backgroundColor: 'rgba(0,0,0,0.6)'
  },
}

if (height < width) {
  styles.btnBox.marginTop = 16
  styles.btnAccount.marginTop = 16
  styles.bgImage.paddingTop = 40
}


export default styles
